spring.application.name=character-api
spring.datasource.url=jdbc:postgresql://ep-super-cake-aiuqidl8-pooler.c-4.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_IaeGySbuA72r&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_IaeGySbuA72r

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect